fix(list-payment) : discount on credit card if is enable on banking_billet only
ecomplus/app-pagarme pull request #84
Opened 2022-09-05 00:53 UTC by matheusgnreis

2022-09-05 00:57 UTC, matheusgnreis commented
Basicamente, quando colocava desconto no boleto, antes não checava exatamente a forma de pagamento que estava dando desconto, apenas se o desconto estava configurado e já subtraia o amount.total, o que gerava um parcelamento errado no addInstallments. Fiz para corrigir isso e também permitir aplicar desconto somente a vista se configurado e suportar o modelo antigo também já configurado. Porém preciso implementar para modules api para validar o novo valor. De toda forma o bug inicial, está corrigido por isso ai.

2022-09-11 06:15 UTC, leomp12 requested changes
Tem uma diff enorme no list payments que acho que não deveria existir, o que está de fato sendo fixado ali?
Em contrapartida não vi checando em lugar o número de parcelas para aplicar o desconto, não é essa a proposta?
No list payments você nem tem o número de parcelas nos parâmetros, portanto não há o que alterar no list payments (ainda), como você vai saber que tem mais de uma parcela para, se assim configurado, não aplicar o desconto?

2022-09-11 06:15 UTC, leomp12 commented on assets/README
> +App base URI: https://us-central1-ecom-pagme.cloudfunctions.net/app/
Nope

2022-09-11 06:15 UTC, leomp12 commented on assets/application.json
>    "auth_scope": {
Nope

2022-09-11 06:15 UTC, leomp12 commented on functions/routes/ecom/modules/list-payments.js
> +        discount[paymentMethod] = discount[paymentMethod] === 'Todas parcelas' || (typeof discount[paymentMethod] === 'boolean' && discount[paymentMethod])
Que ornitorrinco é esse em forma de if?

2022-09-11 06:15 UTC, leomp12 commented on functions/ecom.config.js
> +              'Todas parcelas'
```suggestion
              'Todas as parcelas'
```

2022-09-11 06:22 UTC, leomp12 commented
> Basicamente, quando colocava desconto no boleto, antes não checava exatamente a forma de pagamento que estava dando desconto, apenas se o desconto estava configurado e já subtraia o amount.total, o que gerava um parcelamento errado no addInstallments.

Ah tá, isso não tem nada a ver com N parcelas, é só restrição de desconto por forma de pagamento mesmo...
Tinha ficado confuso pra mim pelo issue e pelas alterações na PR.

> Fiz para corrigir isso e também permitir aplicar desconto somente a vista se configurado e suportar o modelo antigo também já configurado. Porém preciso implementar para modules api para validar o novo valor. De toda forma o bug inicial, está corrigido por isso ai.

Da forma que você fez aí está muito longe de funcionar na verdade essa opção de desconto só em 1x, sua PR deveria só fixar o bug dos descontos por forma de pagamento. Uma outra PR pode implementar essa feature nova, mas também deve ser de forma bem mais simples e de fato deve ter que alterar algo na API de módulos e no front também, antes daqui.

2022-09-11 06:41 UTC, leomp12 commented
O mais difícil era identificar o problema no `amount.total` sendo alterado, isso você fez, mas aí a implementação na PR é muito confusa depois 😐

2022-09-11 06:44 UTC, closed without merging